/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccountSettings: () => import('#controllers/account_settings_controller'),
  Apps: () => import('#controllers/apps_controller'),
  AuditLogs: () => import('#controllers/audit_logs_controller'),
  AuthSettings: () => import('#controllers/auth_settings_controller'),
  Consent: () => import('#controllers/consent_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  Directory: () => import('#controllers/directory_controller'),
  Oauth: () => import('#controllers/oauth_controller'),
  Password: () => import('#controllers/password_controller'),
  RolesAccess: () => import('#controllers/roles_access_controller'),
  Session: () => import('#controllers/session_controller'),
  TwoFactor: () => import('#controllers/two_factor_controller'),
}
