/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AccountSchema extends BaseModel {
  static $columns = ['accessToken', 'accessTokenExpiresAt', 'accountId', 'createdAt', 'id', 'idToken', 'passwordChangedAt', 'passwordHash', 'providerId', 'refreshToken', 'refreshTokenExpiresAt', 'scope', 'updatedAt', 'userId'] as const
  $columns = AccountSchema.$columns
  @column()
  declare accessToken: string | null
  @column.dateTime()
  declare accessTokenExpiresAt: DateTime | null
  @column()
  declare accountId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare idToken: string | null
  @column.dateTime()
  declare passwordChangedAt: DateTime
  @column()
  declare passwordHash: string | null
  @column()
  declare providerId: string
  @column()
  declare refreshToken: string | null
  @column.dateTime()
  declare refreshTokenExpiresAt: DateTime | null
  @column()
  declare scope: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class AppSchema extends BaseModel {
  static $columns = ['createdAt', 'deletedAt', 'description', 'id', 'isActive', 'name', 'slug', 'updatedAt'] as const
  $columns = AppSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class AppEntitlementSchema extends BaseModel {
  static $columns = ['appId', 'enabled', 'grantedAt', 'grantedBy', 'id', 'userId'] as const
  $columns = AppEntitlementSchema.$columns
  @column()
  declare appId: string
  @column()
  declare enabled: boolean
  @column.dateTime()
  declare grantedAt: DateTime
  @column()
  declare grantedBy: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string
}

export class AuditLogSchema extends BaseModel {
  static $columns = ['action', 'actorId', 'createdAt', 'geo', 'id', 'ipAddress', 'metadata', 'resourceId', 'resourceType', 'severity', 'status'] as const
  $columns = AuditLogSchema.$columns
  @column()
  declare action: string
  @column()
  declare actorId: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare geo: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare metadata: any
  @column()
  declare resourceId: string | null
  @column()
  declare resourceType: string | null
  @column()
  declare severity: string
  @column()
  declare status: string
}

export class AuthMethodSchema extends BaseModel {
  static $columns = ['config', 'enabled', 'id', 'key', 'name', 'updatedAt'] as const
  $columns = AuthMethodSchema.$columns
  @column()
  declare config: any
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OauthAuthorizationCodeSchema extends BaseModel {
  static $columns = ['amr', 'authTime', 'codeChallenge', 'codeChallengeMethod', 'codeHash', 'createdAt', 'expiresAt', 'id', 'nonce', 'oauthClientId', 'redirectUri', 'scopes', 'usedAt', 'userId'] as const
  $columns = OauthAuthorizationCodeSchema.$columns
  @column()
  declare amr: any | null
  @column.dateTime()
  declare authTime: DateTime | null
  @column()
  declare codeChallenge: string | null
  @column()
  declare codeChallengeMethod: string | null
  @column()
  declare codeHash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nonce: string | null
  @column()
  declare oauthClientId: string
  @column()
  declare redirectUri: string
  @column()
  declare scopes: any
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: string
}

export class OauthClientSchema extends BaseModel {
  static $columns = ['appId', 'clientId', 'clientSecretHash', 'createdAt', 'deletedAt', 'id', 'postLogoutRedirectUris', 'redirectUris', 'requirePkce', 'tokenEndpointAuthMethod', 'updatedAt'] as const
  $columns = OauthClientSchema.$columns
  @column()
  declare appId: string | null
  @column()
  declare clientId: string
  @column()
  declare clientSecretHash: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare postLogoutRedirectUris: any
  @column()
  declare redirectUris: any
  @column()
  declare requirePkce: boolean
  @column()
  declare tokenEndpointAuthMethod: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class OauthGrantSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'lastUsedAt', 'oauthClientId', 'previousRefreshTokenHash', 'refreshExpiresAt', 'refreshTokenHash', 'revokedAt', 'revokedReason', 'scopes', 'updatedAt', 'userId'] as const
  $columns = OauthGrantSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare oauthClientId: string
  @column()
  declare previousRefreshTokenHash: string | null
  @column.dateTime()
  declare refreshExpiresAt: DateTime | null
  @column()
  declare refreshTokenHash: string | null
  @column.dateTime()
  declare revokedAt: DateTime | null
  @column()
  declare revokedReason: string | null
  @column()
  declare scopes: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class PasswordHistorySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'passwordHash', 'userId'] as const
  $columns = PasswordHistorySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare passwordHash: string
  @column()
  declare userId: string
}

export class PasswordPolicySchema extends BaseModel {
  static $columns = ['extraRules', 'historyCount', 'id', 'maxAgeDays', 'minLength', 'requireLowercase', 'requireNumber', 'requireSpecial', 'requireUppercase', 'updatedAt', 'updatedBy'] as const
  $columns = PasswordPolicySchema.$columns
  @column()
  declare extraRules: any
  @column()
  declare historyCount: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare maxAgeDays: number | null
  @column()
  declare minLength: number
  @column()
  declare requireLowercase: boolean
  @column()
  declare requireNumber: boolean
  @column()
  declare requireSpecial: boolean
  @column()
  declare requireUppercase: boolean
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare updatedBy: string | null
}

export class PermissionSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'key', 'section'] as const
  $columns = PermissionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare key: string
  @column()
  declare section: string
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RoleSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'isSystem', 'name', 'updatedAt'] as const
  $columns = RoleSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isSystem: boolean
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RolePermissionSchema extends BaseModel {
  static $columns = ['permissionId', 'roleId'] as const
  $columns = RolePermissionSchema.$columns
  @column()
  declare permissionId: string
  @column({ isPrimary: true })
  declare roleId: string
}

export class SessionSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'geo', 'id', 'ipAddress', 'token', 'updatedAt', 'userAgent', 'userId'] as const
  $columns = SessionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare geo: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare ipAddress: string | null
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userAgent: string | null
  @column()
  declare userId: string
}

export class TwoFactorSchema extends BaseModel {
  static $columns = ['backupCodesHashed', 'createdAt', 'enabled', 'failedAttempts', 'id', 'lastUsedStep', 'lockedUntil', 'secretEncrypted', 'updatedAt', 'userId', 'verifiedAt'] as const
  $columns = TwoFactorSchema.$columns
  @column()
  declare backupCodesHashed: any
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column()
  declare failedAttempts: number
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare lastUsedStep: number | null
  @column.dateTime()
  declare lockedUntil: DateTime | null
  @column()
  declare secretEncrypted: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column.dateTime()
  declare verifiedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarPath', 'banReason', 'bannedAt', 'createdAt', 'deletedAt', 'email', 'emailVerified', 'emailVerifiedAt', 'id', 'image', 'imagePath', 'name', 'roleId', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarPath: string | null
  @column()
  declare banReason: string | null
  @column.dateTime()
  declare bannedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare deletedAt: DateTime | null
  @column()
  declare email: any
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare image: string | null
  @column()
  declare imagePath: string | null
  @column()
  declare name: string | null
  @column()
  declare roleId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class VerificationSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'id', 'identifier', 'updatedAt', 'userId', 'value'] as const
  $columns = VerificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare identifier: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string | null
  @column()
  declare value: string
}
